# You can find this here : https://prometheus.io/download/#node_exporter
node_exporter_name: node_exporter-1.5.0.linux-amd64
node_exporter_url: https://github.com/prometheus/node_exporter/releases/download/v1.5.0/node_exporter-1.5.0.linux-amd64.tar.gz
node_exporter_checksum: sha256:af999fd31ab54ed3a34b9f0b10c28e9acee9ef5ac5a5d5edfdde85437db7acbb
