- name: install nginx
  apt:
    pkg:
      - nginx

- name: generate html
  template:
    src: default.html.j2
    dest: /var/www/html/index.nginx-debian.html
    mode: 0644
    owner: root
    group: root

- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: true
