node_exporter:
  - instance: glpi
    scrapeUrl: 10.32.41.60:9100

#  - instance: ansible
#    scrapeUrl: 10.32.41.70:9100

#  - instance: prometheus
#    scrapeUrl: 10.32.70.2:9100

  - instance: elk
    scrapeUrl: 10.32.70.3:9100

#  - instance: truenas
#    scrapeUrl: 10.32.97.1:9100

  - instance: haproxy
    scrapeUrl: 10.32.42.1:9100

  - instance: web1
    scrapeUrl: 10.32.42.3:9100

  - instance: web2
    scrapeUrl: 10.32.42.4:9100

  - instance: bdd
    scrapeUrl: 10.32.43.1:9100

  - instance: wazuh
    scrapeUrl: 10.32.72.1:9100

win_exporter:
  - instance: AD
    scrapeUrl: 10.32.41.1:9182

  - instance: ADnoUI
    scrapeUrl: 10.32.41.2:9182

  - instance: VEEAM
    scrapeUrl: 10.32.41.50:9182
