- hosts: localhost
  any_errors_fatal: True
  become: yes
  become_user: root
  vars_files:
    - ../../../../vars/secrets.yml
    - vars/monitoring-directory.yml
  tasks:
    - name: Create the configmap for prometheus
      k8s:
        state: present
        definition:
          apiVersion: v1
          kind: ConfigMap
          metadata:
            namespace: sysadmin
            name: prometheus-server-conf
            labels:
              name: prometheus-server-conf
          data:
            prometheus.yml: "{{ lookup('template', 'prometheus.yml.j2') }}"
            prometheus.rules: "{{ lookup('template', 'prometheus.rules.j2') }}"
            blackbox_https.rules: "{{ lookup('file', 'blackbox_https.rules') }}"
            postgresql.rules: "{{ lookup('template', 'postgresql.rules.j2') }}"
            files.rules: "{{ lookup('file', 'files.rules') }}"

    - name:
      shell: kubectl -n sysadmin scale deployment/prometheus-deployment --replicas=0

    - name:
      shell: kubectl -n sysadmin scale deployment/prometheus-deployment --replicas=1