- name: install easy-rsa
  apt:
    pkg:
      - easy-rsa
      - acl
        
- name: create user authority
  user:
    name: authority
    state: present

- name: mkdir easy-rsa
  become: true
  become_user: authority
  ansible.builtin.file:
    path: /home/authority/easy-rsa
    state: directory
    owner: authority
    group: authority
    mode: '0700'

- name: ln
  ansible.builtin.command: ln -s /usr/share/easy-rsa/* /home/authority/easy-rsa/
