---
- name: "Get checksum for snmp exporter"
  ansible.builtin.set_fact:
    snmp_exporter_checksum: "{{ item.split(' ')[0] }}"
  with_items:
    - "{{ lookup('url', snmp_exporter_checksums_url, wantlist=True) | list }}"
  when: "('linux-' + (go_arch_map[ansible_architecture] | default(ansible_architecture)) + '.tar.gz') in item"
