---
- name: Reload snmp exporter
  listen: "reload snmp exporter"
  ansible.builtin.systemd:
    daemon_reload: true
    name: snmp_exporter
    state: reloaded

- name: Restart snmp exporter
  listen: "restart snmp exporter"
  ansible.builtin.systemd:
    daemon_reload: true
    name: snmp_exporter
    state: restarted
