- hosts: www1
  any_errors_fatal: True
  become: yes
  become_user: root
  tasks:
    
    - name: add gpg key from wazuh repo
      ansible.builtin.shell: "curl -s https://packages.wazuh.com/key/GPG-KEY-WAZUH | gpg --no-default-keyring --keyring gnupg-ring:/usr/share/keyrings/wazuh.gpg --import && chmod 644 /usr/share/keyrings/wazuh.gpg"


    - name: add grafana repository
      become: true
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/wazuh.gpg] https://packages.wazuh.com/4.x/apt/ stable main
        state: present

#    - name: update cache
#      become: true
#      ansible.builtin.apt:
#        update_cache: yes

#    - name: insert var + install wazuh agent
#      become: true
#      ansible.builtin.command: "WAZUH_MANAGER='10.32.72.1' && apt install wazuh-agent"

    - name: install wazuh agent
      become: true
      ansible.builtin.apt:
        update_cache: yes
        pkg:
          - wazuh-agent
      environment:
        WAZUH_MANAGER: "10.32.72.1"

        


    - name: Just force systemd to reread configs (2.4 and above)
      become: true
      ansible.builtin.systemd:
        daemon_reload: true

    - name: Enable service wazuh and ensure it is not masked
      ansible.builtin.systemd:
        name: wazuh-agent
        enabled: true
        masked: no

    - name: restart service
      become: true
      ansible.builtin.service:
        name: wazuh-agent
        state: started
        enabled: true



