# roles/elk/tasks/main.yml
- name: add apt key from elastic
  ansible.builtin.shell: "test -f /usr/share/keyrings/elastic.gpg || curl -fsSL https://artifacts.elastic.co/GPG-KEY-elasticsearch |sudo gpg --dearmor -o /usr/share/keyrings/elastic.gpg"

- name: add elastic repository
  become: true
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/elastic.gpg] https://artifacts.elastic.co/packages/7.x/apt stable main
    state: present

- name: install filebeat
  become: true
  apt:
    pkg: 
      - filebeat

- name: demande de certificat
  ansible.builtin.import_role:
    name: reqsign
  vars:
    cert_dir: "/etc/filebeat/certs"
    type: "client"
    convert: true

- name: ssl config
  ansible.builtin.template:
    src: filebeat.yml.j2
    dest: /etc/filebeat/filebeat.yml

- name: config vers logstash 1
  become: true
  ansible.builtin.command: filebeat modules enable system

- name: config vers logstash 2
  become: true
  ansible.builtin.command: sudo filebeat setup --pipelines --modules system

- name: config vers logstash 3
  become: true
  ansible.builtin.command: filebeat setup --index-management -E output.logstash.enabled=false -E 'output.elasticsearch.hosts=["10.32.70.3:9200"]'

- name: config vers logstash 4
  become: true
  ansible.builtin.command: filebeat setup -E output.logstash.enabled=false -E output.elasticsearch.hosts=['10.32.70.3:9200'] -E setup.kibana.host=10.32.70.3:5601

- name: restart filebeat
  become: true
  ansible.builtin.service:
    name: filebeat
    state: started
    enabled: true

