- name: install openssl
  apt:
    pkg:
      - openssl
      - rsync

- name: gen rsa key
  become: true
  ansible.builtin.command: openssl genrsa -out /etc/ssl/private/web.key

- name: gen req
  become: true
  ansible.builtin.command: openssl req -new -key /etc/ssl/private/web.key -out /tmp/{{ hostname }}.req -subj /C=FR/ST=NORD/L=LILLE/O=GastonMedilab/OU=Community/CN={{ hostname }}

- name: droit
  become: true
  ansible.builtin.file: 
    path: /tmp/{{ hostname }}.req
    mode: '0644'

- name: scp to CA
  synchronize:
    src: /tmp/{{ hostname }}.req
    dest: /tmp/web.req
    mode: pull
  delegate_to: ca.azeroth.wow
  #ssh-agent??

- name: import req
  delegate_to: ca.azeroth.wow
  become: true
  become_user: authority
  ansible.builtin.command: /home/authority/easy-rsa/./easyrsa import-req /tmp/web.req {{ hostname }}
