node_exporter:
  - instance: glpi
    scrapeurl: 10.32.41.60:9100

  - instance: ansible
    scrapeurl: 10.32.41.70:9100

  - instance: prometheus
    scrapeurl: 10.32.70.2:9100

  - instance: elk
    scrapeurl: 10.32.70.3:9100

  - instance: truenas
    scrapeurl: 10.32.97.1:9100

  - instance: haproxy
    scrapeurl: 10.32.42.1:9100

  - instance: web1
    scrapeurl: 10.32.42.3:9100

  - instance: web2
    scrapeurl: 10.32.42.4:9100

  - instance: bdd
    scrapeurl: 10.32.43.1:9100


