# roles/common/tasks/main.yml
- name: install vim sudo curl
  apt:
    pkg: 
      - sudo
      - vim
      - curl


# install filebeat

- name: install filebeat
# voir modules ansible apt 


# install glpi-agent
# exporter prometheus
# set sudoer
# set ssh key

#ssh-addkey.yml

- name: install ssh key
  authorized_key: 
        user=dwilliam
        key="{{ lookup('file', '/home/watchtower/ansible/roles/common/files/william.pub') }}" 
        state=present

- name: install ssh key
  authorized_key: user=dusartc
                  key="{{ lookup('file', '/home/watchtower/ansible/roles/common/files/clement.pub') }}" 
                  state=present

- name: install ssh key
  authorized_key: user=dromaric
                  key="{{ lookup('file', '/home/watchtower/ansible/roles/common/files/romaric.pub') }}" 
                  state=present
# set ntp
