# roles/common/tasks/main.yml
- name: install vim sudo curl
  become: true
  apt:
    pkg: 
      - sudo
      - vim
      - curl
      - wget
      - gpg
    update_cache: yes

# install glpi-agent
- name: copy agent to /tmp
  ansible.builtin.copy:
    src: glpi-agent-1.4-linux-installer.pl
    dest: /tmp/glpi-agent
    mode: 0755
 
- name: install glpi agent
  become: true
  ansible.builtin.command: perl /tmp/glpi-agent -S -s http://glpi.azeroth.wow/glpi/front/inventory.php --runnow

# set ntp
# install ca
- name: install ca
  become: true
  ansible.builtin.copy:
    src: /home/watchtower/ansible/roles/common/files/ca.crt
    dest: /usr/local/share/ca-certificates/gaston.medilab.crt

- name: update ca
  become: true
  ansible.builtin.command: update-ca-certificates

