# You can find this here : https://prometheus.io/download/
prometheus_name: prometheus-2.43.0.linux-amd64
prometheus_url: https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
prometheus_checksum: sha256:cfea92d07dfd9a9536d91dff6366d897f752b1068b9540b3e2669b0281bb8ebf
