# roles/reqsign/sign.yml

# upload les csr
- name: upload csr
  ansible.builtin.copy:
    src: "/tmp/{{ item }}/{{ cert_dir }}/{{ item }}-ansible.req"
    dest: "/tmp"
  loop: {{ old_hosts }}
  when: {{ inventory_hostname }} == 'ca'
